repos:
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      args: [--safe, --quiet]
#      exclude: tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
- repo: https://github.com/PyCQA/pylint
  rev: v2.11.1
  hooks:
    - id: pylint
